// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWqcHILsW5FwbRUigO4l9vHveM8ePtaEw',
    appId: '1:390719619248:web:14129780376ffe2d98fb75',
    messagingSenderId: '390719619248',
    projectId: 'norse-fiber-367205',
    authDomain: 'norse-fiber-367205.firebaseapp.com',
    storageBucket: 'norse-fiber-367205.appspot.com',
    measurementId: 'G-34N4JR4D4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJN4HauaPwt5bi8QaCb4xOqe-idoqIlvQ',
    appId: '1:390719619248:android:91c4999ef87b6b6698fb75',
    messagingSenderId: '390719619248',
    projectId: 'norse-fiber-367205',
    storageBucket: 'norse-fiber-367205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA94-kBFAFSFiFEIxS_skAkpLTVRjucSR4',
    appId: '1:390719619248:ios:daa93ed08de2ed8298fb75',
    messagingSenderId: '390719619248',
    projectId: 'norse-fiber-367205',
    storageBucket: 'norse-fiber-367205.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA94-kBFAFSFiFEIxS_skAkpLTVRjucSR4',
    appId: '1:390719619248:ios:1bd0b287e8e85b9498fb75',
    messagingSenderId: '390719619248',
    projectId: 'norse-fiber-367205',
    storageBucket: 'norse-fiber-367205.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
